Version 2 Vivaann Welfare Association
ajitzero/vivaann pull request #3
Opened 2021-07-13 09:17 UTC by abhirajsinghchauhan

Updated the styling and team member details for the batch 2020.

2021-07-13 12:38 UTC, ajitzero requested changes
Restore these files:
- `.gitignore`
- `LICENSE`

2021-07-13 12:47 UTC, ajitzero requested changes
Also, don't use HEIC files like `img/bhargav-error.HEIC`

2021-07-13 12:47 UTC, ajitzero commented on README.md
> +Version 1 Designed & built by [Ajit Panigrahi](https://twitter.com/ajitzero).
Remove my name and add:

"Currently maintained and managed by [Abhiraj Singh Chauhan](https://www.linkedin.com/in/abhirajsinghchauhan/)"

Add your name in the release (I'll add that once this gets merged)

2021-07-13 12:47 UTC, ajitzero commented on index.html
> +<html>
revert `lang="en"`

2021-07-13 12:47 UTC, ajitzero commented on index.html
> -	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
These `<meta>` tags are necessary for mobile view. I don't think your new website works for mobile view. Please work on that, as a new website should not break anything that used to work previously.

2021-07-13 12:47 UTC, ajitzero commented on style.css
> -@charset "UTF-8";
Add the `@charset` back

2021-07-13 12:53 UTC, ajitzero commented
@abhirajsinghchauhan Thank you for the effort put in this new website. Please ensure these things are met:
- Website should work well on mobile (see [comment](https://github.com/vivaann/vivaann.github.io/pull/3#discussion_r668726304))
- Images should be optimized: use standard web file formats like PNG or JPEG and ensure they are less than 1MB.
- Maintain decent lighthouse scores and fix basic issues (like [this](https://github.com/vivaann/vivaann.github.io/pull/3#discussion_r668724674))

A suggestion: add a separate "Our Team" page for the full list of members and only show few names on the home page. Please add a section to show the members by year, so that at least we can mention the seniors who built Vivaann before us.

2021-07-17 15:08 UTC, abhirajsinghchauhan commented
Hey @ajitzero. 
I appreciate your time and thanks for all the reviews you made. I am going to make a new pull request soon. As of now, I am closing this PR.

2021-07-17 15:08 UTC, closed without merging